-- START SAK-51950
CREATE INDEX CALENDAR_EVENT_CID_RSTART_REND_ESTART
  ON CALENDAR_EVENT (CALENDAR_ID, RANGE_START, RANGE_END, EVENT_START);
-- END SAK-51950


INSERT INTO mci_schema_migrations (name, executed_at)
VALUES ('sakai_23_4-23_5_mysql_conversion.sql', NOW(6));