widget_title=Onboarding Courses
no_courses=You have no onboarding courses assigned.
no_course=This site is not part of your onboarding courses.
due_date=Due
status_not_started=Not Started
status_in_progress=In Progress
status_completed=Completed
